import { ArrowLeft, Edit3, FolderOpen, ImagePlus, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createFlashcard, createFlashcardCategory, deleteFlashcard, deleteFlashcardCategory, fetchFlashcardCategories, fetchFlashcards, updateFlashcard, updateFlashcardCategory } from "../../services/flashcardService";
import { validateFileSize } from "../../utils/fileValidation";
import ConfirmationModal from "../../components/ConfirmationModal";

const id = (value) => String(value?._id || value?.id || value || "");
const blankCard = (category) => ({ prompt: "", answer: "", translation: "", category: id(category), isPublished: true, image: "", imageFile: null });

function Flashcards() {
  const [cards, setCards] = useState([]), [categories, setCategories] = useState([]), [category, setCategory] = useState(null), [form, setForm] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [categoryName, setCategoryName] = useState(""), [editing, setEditing] = useState(null), [deleting, setDeleting] = useState(null);
  const load = async () => { try { const [loadedCards, loadedCategories] = await Promise.all([fetchFlashcards(), fetchFlashcardCategories()]); setCards(loadedCards); setCategories(loadedCategories); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const categoryCards = useMemo(() => cards.filter((card) => id(card.category) === id(category)), [cards, category]);
  const saveCategory = async (event) => { event.preventDefault(); try { const saved = editing ? await updateFlashcardCategory(id(editing), categoryName) : await createFlashcardCategory(categoryName); setCategories((items) => editing ? items.map((item) => id(item) === id(saved) ? saved : item) : [...items, saved].sort((a, b) => a.name.localeCompare(b.name))); if (editing) setCategory(saved); setCategoryName(""); setEditing(null); } catch (err) { setError(err.message); } };
  const saveCard = async (event) => { event.preventDefault(); if (!form.prompt.trim() || !form.answer.trim()) return setError("Front prompt and back answer are required."); try { setSaving(true); const saved = form.id ? await updateFlashcard(form.id, form) : await createFlashcard(form); setCards((items) => form.id ? items.map((item) => item.id === saved.id ? saved : item) : [saved, ...items]); setCategories(await fetchFlashcardCategories()); setForm(null); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const confirmDelete = async () => { try { if (deleting.type === "category") { await deleteFlashcardCategory(id(deleting.item)); setCategories((items) => items.filter((item) => id(item) !== id(deleting.item))); setCategory(null); } else { await deleteFlashcard(deleting.item.id); setCards((items) => items.filter((item) => item.id !== deleting.item.id)); setCategories((items) => items.map((item) => id(item) === id(category) ? { ...item, cardCount: Math.max(0, item.cardCount - 1) } : item)); } } catch (err) { setError(err.message); } finally { setDeleting(null); } };
  const upload = (file) => { if (!file) return; const message = validateFileSize(file, "Flashcard image"); if (message) return setError(message); setForm((item) => ({ ...item, imageFile: file, image: URL.createObjectURL(file) })); };
  if (loading) return <Page><div className="rounded-2xl bg-white p-10 text-center text-[#765F55]">Loading flashcard categories...</div></Page>;
  if (!category) return <Page><Header title="Flashcard categories" text="Organize practice cards into standalone categories." />{error && <Error error={error} />}<form onSubmit={saveCategory} className="mb-7 flex flex-col gap-3 rounded-2xl border border-[#2D2E30]/10 bg-white p-4 sm:flex-row"><input required maxLength={80} value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="New category name" className="flex-1 rounded-xl border border-[#2D2E30]/15 px-3 py-2.5 outline-none focus:border-[#E58C1A]" /><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2D2E30] px-5 py-2.5 font-bold text-white hover:bg-[#E58C1A]"><Plus size={18} /> Create category</button></form>{categories.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{categories.map((item) => <button key={id(item)} onClick={() => { setCategory(item); setError(""); }} className="group rounded-2xl border border-[#2D2E30]/10 bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-[#E58C1A]/40"><div className="flex items-start justify-between"><span className="rounded-xl bg-[#FFF1CE] p-3 text-[#C97112]"><FolderOpen size={22} /></span><span className="rounded-full bg-[#FFF9EA] px-2.5 py-1 text-xs font-bold text-[#765F55]">{item.cardCount || 0} cards</span></div><h2 className="mt-5 text-lg font-bold text-[#2D2E30]">{item.name}</h2><p className="mt-1 text-sm text-[#765F55]">Open category →</p></button>)}</div> : <Empty />}</Page>;
  return <Page><button onClick={() => { setCategory(null); setForm(null); setError(""); }} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[#765F55] hover:text-[#C97112]"><ArrowLeft size={17} /> All categories</button><Header title={category.name} text={`${categoryCards.length} cards in this category.`} actions={<><button onClick={() => { setEditing(category); setCategoryName(category.name); }} className="button-secondary"><Pencil size={16} /> Rename</button><button disabled={categoryCards.length > 0} title={categoryCards.length ? "Remove all cards before deleting this category" : "Delete category"} onClick={() => setDeleting({ type: "category", item: category })} className="button-danger"><Trash2 size={16} /> Delete</button><button onClick={() => setForm(blankCard(category))} className="button-primary"><Plus size={18} /> Add flashcard</button></>} />{error && <Error error={error} />}{editing && <form onSubmit={saveCategory} className="mb-6 flex gap-3 rounded-2xl bg-[#FFF9EA] p-4"><input autoFocus required value={categoryName} onChange={(e) => setCategoryName(e.target.value)} className="flex-1 rounded-xl border border-[#2D2E30]/15 bg-white px-3 py-2.5 outline-none" /><button className="button-primary">Save</button><button type="button" onClick={() => setEditing(null)} className="button-secondary">Cancel</button></form>}{form && <CardForm form={form} categories={categories} onChange={(field, value) => setForm((item) => ({ ...item, [field]: value }))} onUpload={upload} onSave={saveCard} close={() => setForm(null)} saving={saving} />}{categoryCards.length ? <div className="grid gap-4 md:grid-cols-2">{categoryCards.map((card) => <article key={card.id} className="overflow-hidden rounded-2xl border border-[#2D2E30]/10 bg-white"><div className="flex gap-4 p-4">{card.image ? <img src={card.image} alt="" className="h-20 w-20 rounded-xl object-cover" /> : <div className="flex h-20 w-20 items-center justify-center rounded-xl bg-[#FFF1CE] text-3xl">📝</div>}<div className="min-w-0 flex-1"><p className="font-bold text-[#2D2E30]">{card.prompt}</p><p className="mt-2 font-semibold text-[#C97112]">{card.answer}</p>{card.translation && <p className="mt-1 text-sm text-[#765F55]">{card.translation}</p>}</div></div><div className="flex justify-end gap-2 border-t border-[#2D2E30]/10 p-3"><button onClick={() => setForm({ ...card, category: id(card.category), imageFile: null })} className="button-secondary"><Edit3 size={15} /> Edit</button><button onClick={() => setDeleting({ type: "card", item: card })} className="button-danger"><Trash2 size={15} /> Delete</button></div></article>)}</div> : <Empty message="No flashcards in this category yet." />}<ConfirmationModal isOpen={Boolean(deleting)} title={`Delete ${deleting?.type || ""}`} message="This action cannot be undone." confirmText="Delete" cancelText="Cancel" onConfirm={confirmDelete} onCancel={() => setDeleting(null)} isDangerous /></Page>;
}
function Page({ children }) { return <div className="min-h-screen bg-[#FFFDF8] p-4 sm:p-6 md:p-8"><div className="mx-auto max-w-7xl">{children}</div></div>; }
function Header({ title, text, actions }) { return <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#C97112]">Practice content</p><h1 className="mt-2 text-3xl font-bold text-[#2D2E30] sm:text-4xl">{title}</h1><p className="mt-2 text-[#765F55]">{text}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</header>; }
function CardForm({ form, categories, onChange, onUpload, onSave, close, saving }) { return <form onSubmit={onSave} className="mb-7 rounded-3xl border border-[#E58C1A]/25 bg-[#FFF9EA] p-5"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{form.id ? "Edit" : "New"} flashcard</h2><button type="button" onClick={close}><X /></button></div><div className="grid gap-4 sm:grid-cols-2"><label>Category<select value={form.category} onChange={(e) => onChange("category", e.target.value)} className="input">{categories.map((item) => <option key={id(item)} value={id(item)}>{item.name}</option>)}</select></label><label>Front / question<input required value={form.prompt} onChange={(e) => onChange("prompt", e.target.value)} className="input" /></label><label>Back / answer<input required value={form.answer} onChange={(e) => onChange("answer", e.target.value)} className="input" /></label><label>Translation<input value={form.translation} onChange={(e) => onChange("translation", e.target.value)} className="input" /></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.isPublished} onChange={(e) => onChange("isPublished", e.target.checked)} /> Published publicly</label><label className="flex items-center gap-2"><ImagePlus size={18} /> Image<input type="file" accept="image/*" onChange={(e) => onUpload(e.target.files?.[0])} /></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="button-secondary">Cancel</button><button disabled={saving} className="button-primary">{saving ? "Saving..." : "Save flashcard"}</button></div></form>; }
function Error({ error }) { return <div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>; }
function Empty({ message = "Create a category first, then add its flashcards." }) { return <div className="rounded-2xl border border-dashed border-[#E58C1A]/35 bg-[#FFF9EA] p-10 text-center text-[#765F55]">{message}</div>; }
export default Flashcards;
