import { RotateCcw, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { fetchFlashcards } from "../services/flashcardService";

const SAMPLE = { prompt: "What is this?", answer: "\u0e21\u0e30\u0e21\u0e48\u0e27\u0e07 (mamuang)", translation: "Mango" };
const RATINGS = [{ key: "again", label: "Again", score: 0, note: "Didn't remember", style: "bg-[#FDE8E5] text-[#A34D45]" }, { key: "hard", label: "Hard", score: .5, note: "Partially remembered", style: "bg-[#FFF1CE] text-[#9A5816]" }, { key: "easy", label: "Easy", score: 1, note: "Remembered", style: "bg-[#E9F4EA] text-[#246B35]" }];

function Flashcards() {
  const [cards, setCards] = useState([]), [index, setIndex] = useState(0), [flipped, setFlipped] = useState(false), [ratings, setRatings] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { fetchFlashcards().then(setCards).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const deck = cards.length ? cards : error ? [] : [SAMPLE], card = deck[index], complete = index >= deck.length && deck.length > 0;
  const score = useMemo(() => ratings.reduce((total, item) => total + item.score, 0), [ratings]);
  const choose = (rating) => { setRatings((items) => [...items, rating]); setFlipped(false); setIndex((current) => current + 1); };
  const reset = () => { setIndex(0); setFlipped(false); setRatings([]); };
  return <div className="flex min-h-screen flex-col bg-[#FFF9EA] text-[#2D2E30]"><Navbar /><main className="relative isolate flex-1 overflow-hidden px-4 py-12 sm:px-6 md:py-16"><div className="absolute -left-28 top-0 -z-10 h-80 w-80 rounded-full bg-[#F8C56A]/25 blur-3xl" /><div className="mx-auto w-full max-w-3xl"><header className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFF1CE] text-[#C97112]"><Sparkles /></div><p className="mt-4 text-xs font-bold uppercase tracking-[.2em] text-[#C97112]">Free practice - no login needed</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Flashcards</h1><p className="mt-3 text-[#765F55]">Click a card to flip it, then rate how well you remembered it.</p></header>{loading ? <div className="mt-10 rounded-3xl bg-white p-10 text-center text-[#765F55]">Loading flashcards...</div> : error ? <div className="mt-10 rounded-3xl border border-red-200 bg-red-50 p-8 text-center text-red-700">{error}</div> : complete ? <Results deck={deck} score={score} ratings={ratings} reset={reset} /> : card ? <section className="mt-10"><div className="mb-4 flex justify-between text-sm font-semibold text-[#765F55]"><span>Flashcard {index + 1} of {deck.length}</span><span>{ratings.length} reviewed</span></div><div className="h-2 overflow-hidden rounded-full bg-[#E9DED2]"><div className="h-full bg-[#E58C1A] transition-all" style={{ width: `${index / deck.length * 100}%` }} /></div><FlashCard card={card} flipped={flipped} onFlip={() => setFlipped((current) => !current)} />{flipped ? <div className="mt-5 grid grid-cols-3 gap-3">{RATINGS.map((rating) => <button key={rating.key} type="button" onClick={() => choose(rating)} className={`rounded-2xl px-3 py-4 font-bold transition hover:brightness-95 ${rating.style}`}><span className="block">{rating.label}</span><span className="mt-1 block text-[11px] font-medium opacity-75">{rating.note}</span></button>)}</div> : <p className="mt-5 text-center text-sm font-semibold text-[#765F55]">Click the card to reveal the answer.</p>}</section> : <div className="mt-10 rounded-3xl bg-white p-10 text-center">No flashcards published yet.</div>}</div></main><Footer /></div>;
}

function FlashCard({ card, flipped, onFlip }) {
  const face = { position: "absolute", inset: 0, display: "flex", minHeight: 380, flexDirection: "column", alignItems: "center", justifyContent: "center", overflow: "hidden", borderRadius: "2rem", background: "white", padding: "1.75rem", textAlign: "center", boxShadow: "0 24px 55px -35px rgba(45,46,48,.55)", backfaceVisibility: "hidden", WebkitBackfaceVisibility: "hidden" };
  return <button type="button" onClick={onFlip} aria-pressed={flipped} aria-label={flipped ? "Show flashcard front" : "Show flashcard back"} className="mt-5 block w-full rounded-[2rem] text-inherit focus:outline-none focus:ring-4 focus:ring-[#E58C1A]/30" style={{ perspective: "1200px" }}><div style={{ position: "relative", minHeight: 380, width: "100%", transformStyle: "preserve-3d", transition: "transform 500ms ease", transform: flipped ? "rotateY(180deg)" : "rotateY(0deg)" }}><div style={face}><p className="text-xs font-bold uppercase tracking-[.18em] text-[#C97112]">Front - click to flip</p>{card.image ? <img src={card.image} alt="Flashcard prompt" className="mt-5 h-40 w-56 rounded-2xl object-cover shadow-sm" /> : <div className="mt-7 text-7xl" aria-hidden="true">Mango</div>}<h2 className="mt-6 text-3xl font-bold sm:text-4xl">{card.prompt}</h2></div><div style={{ ...face, transform: "rotateY(180deg)" }}><p className="text-xs font-bold uppercase tracking-[.18em] text-[#C97112]">Back - click to flip</p><h2 className="mt-5 text-3xl font-bold leading-relaxed sm:text-4xl">{card.answer}</h2>{card.translation && <p className="mt-3 text-xl text-[#765F55]">{card.translation}</p>}</div></div></button>;
}

function Results({ deck, score, ratings, reset }) { return <section className="mt-10 rounded-3xl bg-white p-8 text-center shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#C97112]">Deck complete</p><h2 className="mt-2 text-3xl font-bold">Your score: {Math.round(score / deck.length * 100)}%</h2><p className="mt-2 text-[#765F55]">{score % 1 ? score.toFixed(1) : score} / {deck.length} points</p><div className="mx-auto mt-7 grid max-w-md grid-cols-3 gap-3">{RATINGS.map((rating) => <div key={rating.key} className="rounded-2xl bg-[#FFF9EA] p-3"><p className="text-2xl font-bold">{ratings.filter((item) => item.key === rating.key).length}</p><p className="text-xs font-semibold text-[#765F55]">{rating.label}</p></div>)}</div><button type="button" onClick={reset} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#2D2E30] px-5 py-3 font-bold text-white hover:bg-[#E58C1A]"><RotateCcw size={17} /> Study again</button></section>; }

export default Flashcards;
