import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export const LEGAL_DOCUMENT_CLASS = "legal-document mx-auto w-full max-w-screen-xl";

function LegalPolicy({ title, summary, sections, lastUpdated }) {
  return <div className="flex min-h-screen flex-col bg-[#FFF9EA] text-[#2D2E30]"><Navbar /><main className="flex-1 border-y border-[#E58C1A]/10 bg-[#FFFDF8] px-4 py-10 sm:px-6 sm:py-12 lg:px-10 lg:py-14"><article className={LEGAL_DOCUMENT_CLASS}><header className="max-w-6xl border-b border-[#2D2E30]/10 pb-8"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#C97112]">Arun Thai Language Center</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">{title}</h1>{lastUpdated && <p className="mt-3 text-sm font-medium text-[#765F55]">Last updated: {lastUpdated}</p>}<p className="mt-4 max-w-6xl text-justify text-base leading-7 text-[#765F55] sm:text-lg">{summary}</p></header><div className="space-y-9 py-9"><div className="max-w-6xl space-y-9">{sections.map((section) => <section key={section.heading}><h2 className="text-xl font-bold tracking-tight sm:text-2xl">{section.heading}</h2><div className="mt-3 space-y-3 text-justify text-sm leading-7 text-[#765F55] sm:text-base">{(Array.isArray(section.content) ? section.content : [section.content]).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}</div></div></article></main><Footer /></div>;
}

export function PrivacyPolicy() {
  return <LegalPolicy title="Privacy Policy" lastUpdated="September 2026" summary="Arun Thai Language Center (“Arun Thai”, “we”, “us”, or “our”) operates the Arun Thai website and online learning service. This Privacy Policy explains what information we collect, why we collect it, how we use it, and the choices you have when using our website and services. For privacy questions or requests, contact arunthaiedu@gmail.com." sections={[
    { heading: "1. Information We Collect", content: ["Depending on how you use Arun Thai, we may collect account information such as your name and email address; login and security information; course enrolment and purchased-course information; learning progress, completion, activity, and quiz-related information; and payment information needed to process and verify course purchases.", "We may also collect uploaded payment proof, payment-method information maintained for verification and records, contact enquiries, marketing preferences, course feedback, testimonial preferences, avatar or photo publication permission where applicable, administrative/security/audit records, and age-eligibility information required for account registration."] },
    { heading: "2. How We Use Your Information", content: ["We use information to create and secure accounts, provide purchased courses, maintain learning progress and activity, process and verify payments, respond to enquiries and support requests, and send necessary account, payment, security, and service communications.", "We also use information to send marketing only where you explicitly opt in; manage private feedback and permitted testimonials; operate and administer Arun Thai; prevent or investigate misuse, suspected fraud, and security problems; and meet necessary legal and payment-related obligations. We aim to collect and use only information reasonably necessary for these purposes."] },
    { heading: "3. Marketing Communications", content: ["Marketing and promotional messages are sent only when you have explicitly opted in. Choosing not to receive marketing does not prevent account creation, course purchases, use of purchased courses, or necessary service communications.", "You may withdraw marketing consent at any time. Unsubscribing does not stop account/security, payment, course/service, legal, enquiry-response, or support communications. Submitting a contact enquiry does not automatically mean that you agreed to receive marketing messages."] },
    { heading: "4. Feedback and Testimonials", content: ["Feedback is private by default. We may review it to understand student experiences and improve our courses and services. If we would like to publish feedback as a testimonial, we will ask for permission before publishing it.", "With permission, we may use your chosen first name or an anonymous presentation. We will not intentionally publish your email address, phone number, or unnecessary personal information. Publishing an avatar or photo requires separate permission. Approved testimonials may be used on Arun Thai-controlled websites or marketing channels within the permission provided. Negative or critical feedback may remain private and be used internally to improve service or resolve a reported issue."] },
    { heading: "5. Withdrawing Testimonial Permission", content: "You may withdraw permission for testimonial use. After receiving a withdrawal request, we will stop future use and remove the testimonial from Arun Thai-controlled channels where reasonably possible. We cannot guarantee removal of copies already reposted, shared, cached, screenshotted, or distributed by unrelated third parties." },
    { heading: "6. Account Deletion", content: ["You may request account deletion through the available account-deletion process or by contacting us. Deleting a learning account does not necessarily mean every connected record is immediately deleted. Learning progress and similar learner state may be deleted according to our deletion process.", "Some information may be retained separately where reasonably necessary for payment records, refunds or disputes, suspected fraud or security investigations, legal obligations, or necessary audit records. Account deletion does not automatically cancel existing payment obligations, disputes, refunds, or other legal requirements."] },
    { heading: "7. Privacy Requests", content: ["Contact arunthaiedu@gmail.com to request access to information we hold, correction of incorrect information, deletion where applicable, or other reasonable privacy-related assistance. We may carry out reasonable identity verification before providing or changing personal information.", "We will not normally request identity documents unless reasonably necessary for the request. If you need information about your data, please contact us directly."] },
    { heading: "8. Third-Party Service Providers", content: "Arun Thai uses third-party services where necessary to operate and support the service. These may include MongoDB for application and database records, Cloudinary for images/payment proofs and related media, Resend for email delivery, and Render for application hosting and infrastructure where applicable. If we introduce additional services that materially change how personal information is collected or used, we may update this Privacy Policy." },
    { heading: "9. Information Retention", content: ["We keep personal information only as long as reasonably necessary to provide services, handle payments and disputes, maintain security, and meet legal obligations. As a general guide, contact enquiries are normally kept for up to one year, payment proofs for around one year after payment review, and certain payment records for up to seven years where necessary for record-keeping or legal purposes. Security and administrative records may be kept for shorter periods depending on purpose.", "Information may be retained longer when reasonably necessary for payment disputes, refunds, security investigations, or legal obligations. Some retention and cleanup processes may be manual, so we do not promise that every record is automatically deleted at an exact time or date."] },
    { heading: "10. Children and Age Requirements", content: "Arun Thai is intended for people aged 13 or older. People aged 12 or younger cannot create an Arun Thai account. We use an age-group or age-confirmation process and do not intentionally collect a date of birth where it is unnecessary. For students aged 13–17, we record the required confirmation that permission has been obtained from a parent or legal guardian; we do not intentionally collect unnecessary guardian identity documents for this purpose." },
    { heading: "11. Security", content: "We take reasonable technical and organizational measures to protect personal information against unauthorized access, loss, misuse, or disclosure. However, no online service can guarantee absolute security." },
    { heading: "12. Changes to This Privacy Policy", content: "We may update this Privacy Policy when services, technology, or privacy practices change. When appropriate, we will provide notice of significant changes through the Arun Thai website or other suitable communication methods. The latest version will be available on this page." },
    { heading: "13. Contact Us", content: "For questions about this Privacy Policy or to make a privacy-related request, contact Arun Thai Language Center at arunthaiedu@gmail.com." },
  ]} />;
}

export function CookiePolicy() {
  return <LegalPolicy title="Cookie & Storage Policy" lastUpdated="September 2026" summary="Arun Thai Language Center uses a small amount of browser storage and cookies to provide essential website functionality and keep your account secure. We do not currently use advertising cookies, analytics tracking tools, or third-party advertising pixels." sections={[
    { heading: "1. Authentication Cookie", content: ["When you sign in to Arun Thai, we use an essential authentication cookie to help keep you securely signed in.", "This cookie is used to maintain your secure login session, restore your session when you return to the website, and protect your account and authentication process.", "This is an essential authentication and security cookie. It is not used for advertising or behavioral tracking.", "We use reasonable security measures to protect the authentication process.", "The authentication cookie may remain active for a limited period to help maintain your session. You may need to sign in again when your session expires."] },
    { heading: "2. Browser Local Storage", content: ["Arun Thai may use your browser's local storage to temporarily save unfinished quiz-related work.", "For example, local storage may help preserve a quiz draft if you leave the page before completing it.", "Information stored in local storage may remain on your device until it is cleared by the website, your browser, or you."] },
    { heading: "3. No Advertising or Analytics Tracking", content: ["At the time this policy was written, Arun Thai does not use advertising cookies, analytics tracking tools, advertising pixels, or similar technologies for behavioral advertising or cross-site tracking.", "We do not currently use cookies or similar technologies to create advertising profiles or track you across unrelated websites."] },
    { heading: "4. Changes to Our Use of Cookies", content: "Our use of cookies and browser storage may change as the Arun Thai website develops. If we introduce analytics, advertising, marketing pixels, or other non-essential tracking technologies in the future, we will review this policy and any applicable consent requirements before using them." },
    { heading: "5. Contact Us", content: "If you have questions about our use of cookies or browser storage, please contact Arun Thai Language Center at arunthaiedu@gmail.com." },
  ]} />;
}

export function Terms() {
  return <LegalPolicy title="Terms & Conditions" lastUpdated="September 2026" summary="Welcome to Arun Thai Language Center. These Terms & Conditions explain the rules for using the Arun Thai website and purchasing or accessing our online language courses. By creating an account, purchasing a course, or using our services, you agree to follow these Terms." sections={[
    { heading: "1. About Arun Thai", content: "Arun Thai provides online language-learning courses and related learning services." },
    { heading: "2. Your Arun Thai Account", content: ["One Account, One Learner. Each Arun Thai account is intended for one learner.", "Your account and purchased course access are personal and cannot be transferred to another person. You may use your account on multiple personal devices. However, account sharing is not allowed.", "You are responsible for keeping your login information secure. If you believe someone has accessed your account without permission, please contact Arun Thai as soon as possible.", "We may take reasonable security measures if we detect suspicious or unauthorized account activity."] },
    { heading: "3. Someone Else Can Pay for Your Course", content: "The person who makes the payment does not have to be the learner. For example, a parent, guardian, family member, or another person may pay for a learner. However, the purchased course remains connected to the learner's Arun Thai account and cannot be transferred to another account." },
    { heading: "4. Course Purchases", content: "Each course is purchased separately. If you want to purchase multiple courses, each course requires its own purchase and payment. Arun Thai does not currently provide a course gift or course-transfer feature." },
    { heading: "5. Pricing and Currency", content: ["Arun Thai currently supports pricing in Thai Baht (THB) and Myanmar Kyat (MMK). Arun Thai may set separate prices for each currency. The THB and MMK prices are not automatically calculated using an exchange rate.", "Before making a payment, you are responsible for checking the displayed price and paying the correct amount for the currency you selected.", "Arun Thai may change course prices from time to time. A new price applies to future purchases. A later price reduction or promotion does not automatically create a refund or adjustment for an earlier purchase."] },
    { heading: "6. Promotions and Discounts", content: ["If a promotion or discount is available, it must be valid and successfully applied before payment. The amount you need to pay is the final price shown after a valid promotion has been applied.", "If you forget to apply a valid promotion and complete the payment at the normal price, a retroactive promotional adjustment will normally not be provided.", "If a promotion has expired or a technical issue results in an incorrect payment amount, Arun Thai may review the situation individually."] },
    { heading: "7. When a Purchase Becomes Final", content: "A course purchase becomes a payment commitment when the student actually transfers or sends the payment. Uploading payment proof does not create a cancellation period. The payment verification process is used to confirm the payment; it is not a period during which you can cancel simply because you changed your mind." },
    { heading: "8. Change-of-Mind Refunds", content: "Arun Thai does not normally provide a refund simply because a student changes their mind after transferring payment. This does not exclude refunds or other remedies that may apply under the payment rules in these Terms or under applicable law." },
    { heading: "9. Overpayment", content: ["If you pay more than the required amount and the payment is successfully verified, Arun Thai will accept the correct purchase amount and return the verified excess amount. For example, if the required payment is 1,000 THB and you transfer 1,200 THB, the additional 200 THB will be returned.", "Arun Thai aims to process or initiate an eligible overpayment refund within up to 10 business days after the necessary refund details have been confirmed. The actual time for the money to reach your account may depend on the bank or payment provider.", "Where possible, refunds will be made to the original payment source. If you request a different payment destination, additional verification may be required.", "Where legally permitted, an unavoidable transfer cost caused by a payment error may be deducted from the amount returned."] },
    { heading: "10. Underpayment", content: "If the amount received is less than the required purchase price, Arun Thai may reject the payment. If the payment is rejected, the amount received will be returned and you will need to make a new payment for the correct amount. An underpayment does not automatically become partial payment for a course." },
    { heading: "11. Duplicate Payments", content: "If you accidentally make the same payment more than once, Arun Thai will verify the duplicate payment. Once verified, Arun Thai will accept one valid payment and return the verified duplicate amount. If Arun Thai identifies an obvious duplicate payment, we may contact you to resolve and return the duplicate payment." },
    { heading: "12. If Arun Thai Cannot Provide Your Course", content: "If Arun Thai is unable to provide a purchased course, we will first try to fix the problem, restore or provide access, or offer an appropriate alternative solution. If Arun Thai genuinely cannot provide the purchased service and an appropriate replacement cannot be agreed upon, the applicable refund or other remedy will be provided. Where a refund is required because Arun Thai cannot provide the purchased service, Arun Thai will bear the relevant transfer cost so that the student receives the full refundable amount." },
    { heading: "13. Payment Verification", content: ["Uploaded payment screenshots or receipts are evidence of payment, not final proof by themselves. Arun Thai may verify payments against the receiving account's transaction records.", "If a payment failed, was reversed, was not received, or cannot reasonably be verified, course access will not be granted merely because a payment screenshot was uploaded.", "When necessary, Arun Thai may ask you to provide additional official evidence from your bank or payment provider. We will not intentionally request unnecessary banking information."] },
    { heading: "14. Payment Proof", content: "Students should submit payment proof after making a payment so that Arun Thai can verify the transaction. As a general rule, no payment proof submitted means course access cannot be confirmed until the student contacts Arun Thai and the payment can be properly handled or verified. Payment-related problems should be reported within 30 calendar days from the actual payment transfer date whenever possible. This reporting period does not remove any rights or remedies that cannot legally be excluded." },
    { heading: "15. Reversed Payments and Chargebacks", content: ["If a payment that was previously approved is later reversed, removed, or otherwise becomes unresolved, Arun Thai may temporarily suspend course access while the payment is investigated. If the payment is later resolved and verified, access may be restored where appropriate.", "A reversed payment or chargeback is not automatically considered fraudulent. However, deliberate fraudulent activity or other serious misuse may be handled as a serious violation of these Terms following appropriate investigation.", "If a previous purchase is reversed and the learner later wants to purchase the course again, a new valid purchase and payment will be required."] },
    { heading: "16. Lifetime Course Access", content: "Purchased courses provide lifetime access. For Arun Thai, this means there is no ordinary course-access expiry while Arun Thai continues operating and is reasonably able to provide that course or service. “Lifetime access” does not mean that Arun Thai guarantees the service will continue to exist for the biological lifetime of a student." },
    { heading: "17. Course Updates", content: "Updates to the same purchased course are included with your existing purchase. This may include updated lessons, replacement videos, corrections, improved exercises, and major updates or refreshes to the same course. If Arun Thai creates a genuinely new or separate course, that course may require a new purchase." },
    { heading: "18. Course Discontinuation", content: "Arun Thai's normal intention is to maintain and update purchased courses rather than simply delete them. If Arun Thai is no longer able to provide a particular purchased course in the future, we will try to continue providing the course or offer an appropriate solution, subject to applicable legal rights and remedies." },
    { heading: "19. Course Materials", content: ["Course materials are provided for your personal learning and ordinary personal notes.", "Without permission from Arun Thai, you may not copy and redistribute course materials, resell course materials, publicly upload course materials, use course materials commercially, provide course materials to other people, or share purchased course access or your account.", "These restrictions do not prevent you from making reasonable personal notes for your own learning."] },
    { heading: "20. Misuse of the Service", content: ["Serious misuse of Arun Thai may include deliberate account sharing, piracy or unauthorized distribution of course materials, fraud or deliberate payment abuse, harassment, threats, deliberate disruption of the service, or other serious misuse of Arun Thai's website, courses, accounts, or content.", "If we identify a serious issue, Arun Thai may temporarily suspend an account while investigating. Depending on the circumstances, possible actions may include restoring access, giving a warning or restriction, continuing a suspension, or terminating the account.", "Cases may be handled individually based on the circumstances and available evidence."] },
    { heading: "21. Serious or Permanent Violations", content: "If an account is permanently terminated because of serious misconduct such as piracy, fraud, repeated deliberate account sharing, or comparable serious violations, creating another account to avoid that termination is not permitted." },
    { heading: "22. Account Deletion", content: ["You may delete your Arun Thai account through the available account deletion process. Deleting your account means you will lose access to courses purchased through that account. Before completing account deletion, you should make sure you understand that purchased course access will no longer be available through the deleted account.", "Learning progress and similar learner information may be deleted according to our account-deletion process. Some payment, security, dispute, or legally required records may continue to be retained separately.", "Deleting an account does not automatically cancel existing refunds, disputes, payment obligations, or legal requirements."] },
    { heading: "23. Age Requirements", content: "Arun Thai is intended for people aged 13 or older. People aged 12 or younger cannot register for an account. Students aged 13–17 must have permission from a parent or legal guardian. By creating an account, you confirm that you meet the applicable age requirement and, where required, have permission from a parent or legal guardian." },
    { heading: "24. Communication", content: "The email address registered with your Arun Thai account is the primary formal communication channel for your account. Arun Thai may also provide notices through the website or inside the application. For material changes to these Terms, Arun Thai intends to notify existing students before the changes become effective. Minor corrections, formatting changes, or clarifications may not require individual notice." },
    { heading: "25. Changes to These Terms", content: "Arun Thai may update these Terms when our services, courses, payment processes, or business practices change. When a change is material, we will provide appropriate notice before the updated Terms become effective. The latest version will be available on the Arun Thai website." },
    { heading: "26. Contact Us", content: "If you have questions about these Terms, your purchase, payment, course access, or any related issue, please contact Arun Thai Language Center at arunthaiedu@gmail.com." },
  ]} />;
}
