import { useParams, useNavigate } from "react-router-dom";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, Check, CircleCheck, Clock3, Maximize2, X, XCircle } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import LoadingSpinner from "../components/LoadingSpinner";
import { fetchMyPayments, fetchRejectedPaymentProofBlob } from "../services/paymentService";
import { orderStatusView, rejectedPaymentResubmissionPath, savedPaymentDetails } from "../utils/orderStatusView";
import { createProofObjectUrl, proofRequestKey, rejectedProofDisplayState, revokeProofObjectUrl, shouldFetchProof, shouldShowRejectedProof } from "../utils/studentProofViewer";

function OrderStatus() {
  const { orderId } = useParams(); const navigate = useNavigate();
  const [payment, setPayment] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { setLoading(true); setError(""); const next = (await fetchMyPayments()).find((item) => item.id === orderId); if (!next) throw new Error("Order not found"); setPayment(next); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } })(); }, [orderId]);
  if (loading) return <Page><div className="flex h-screen items-center justify-center"><LoadingSpinner message="Loading payment status..." /></div></Page>;
  if (!payment || !payment.course) return <Page><div className="flex h-screen items-center justify-center px-4 text-center"><p className="text-lg text-[#765F55] sm:text-2xl">{error || "Order not found"}</p></div></Page>;
  const view = orderStatusView(payment); const details = savedPaymentDetails(payment); const course = payment.course;
  const submittedAt = payment.createdAt ? new Date(payment.createdAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "Date unavailable";
  const isRejected = payment.status === "rejected"; const isApproved = view.kind === "approved";
  return <Page><main className="flex-1 bg-[#FFF9EA] px-4 py-6 sm:px-6 sm:py-8 md:px-10 md:py-10"><div className="mx-auto max-w-3xl">
    <button onClick={() => navigate("/app/orders")} className="inline-flex items-center gap-2 text-sm font-bold text-[#765F55] transition hover:text-[#C97112]"><ArrowLeft className="h-4 w-4" />Course orders</button>
    {isRejected ? <RejectedExperience payment={payment} view={view} course={course} details={details} submittedAt={submittedAt} onSubmit={() => navigate(rejectedPaymentResubmissionPath(course.id))} onStart={() => navigate(`/app/learn/${course.id}`)} onViewCurrent={() => navigate(`/app/orders/${view.currentPaymentId}`)} /> : isApproved ? <ApprovedExperience course={course} details={details} submittedAt={submittedAt} onStart={() => navigate(`/app/learn/${course.id}`)} /> : <PendingExperience course={course} details={details} submittedAt={submittedAt} />}
  </div></main></Page>;
}

function Page({ children }) { return <div className="flex min-h-screen flex-col bg-[#FFFDF8]"><Navbar />{children}<Footer /></div>; }

function PendingExperience({ course, details, submittedAt }) { return <><section className="max-w-2xl pb-8 pt-10 sm:pb-10 sm:pt-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#C97112]">Payment status</p><div className="mt-5 flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#FFF1CE] text-[#C97112]"><Clock3 className="h-5 w-5" /></span><div><h1 className="text-3xl font-bold tracking-tight text-[#2D2E30] sm:text-4xl">Waiting for review</h1><p className="mt-2 max-w-md text-sm leading-6 text-[#765F55] sm:text-base">We’ve received your payment. No action is needed right now.</p></div></div><ProgressTracker left /></section><ReceiptContext course={course} details={details} submittedAt={submittedAt} /></>; }

function ApprovedExperience({ course, details, submittedAt, onStart }) { return <><section className="pb-8 pt-10 text-center sm:pb-10 sm:pt-14"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#E9F4EA] text-[#4D7C57]"><CircleCheck className="h-6 w-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-[#4D7C57]">Enrollment complete</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-[#2D2E30] sm:text-4xl">You’re enrolled!</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#765F55] sm:text-base"><strong className="text-[#2D2E30]">{course.title}</strong> is ready. You can start learning now.</p><button onClick={onStart} className="mt-7 inline-flex w-full items-center justify-center rounded-xl bg-[#F8C56A] px-5 py-3.5 text-sm font-bold text-[#2D2E30] shadow-[0_12px_24px_-18px_rgba(185,97,40,.75)] transition hover:bg-[#E58C1A] sm:w-auto">Start learning <span className="ml-2">→</span></button></section><ReceiptContext course={course} details={details} submittedAt={submittedAt} subdued /></>; }

function RejectedExperience({ payment, view, course, details, submittedAt, onSubmit, onStart, onViewCurrent }) { const resolved = view.kind === "resolved"; const newer = view.kind === "newer_pending" || view.kind === "newer_rejected"; const tone = resolved ? "text-[#4D7C57]" : newer ? "text-[#A66B12]" : "text-[#A34D45]"; const Icon = resolved ? CircleCheck : newer ? Clock3 : XCircle; return <><section className="max-w-2xl pb-7 pt-10 sm:pt-14"><p className={`text-xs font-bold uppercase tracking-[.2em] ${tone}`}>{view.eyebrow}</p><div className="mt-5 flex items-start gap-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${resolved ? "bg-[#E9F4EA] text-[#4D7C57]" : newer ? "bg-[#FFF1CE] text-[#A66B12]" : "bg-[#FFF0EE] text-[#A34D45]"}`}><Icon className="h-5 w-5" /></span><div><h1 className="text-3xl font-bold tracking-tight text-[#2D2E30] sm:text-4xl">{view.title}</h1><p className="mt-2 text-sm leading-6 text-[#765F55] sm:text-base">{view.description}</p></div></div>{resolved ? <button onClick={onStart} className="mt-6 inline-flex w-full items-center justify-center rounded-xl bg-[#F8C56A] px-5 py-3.5 text-sm font-bold text-[#2D2E30] sm:w-auto">Start learning <span className="ml-2">→</span></button> : newer ? <button onClick={onViewCurrent} className="mt-6 inline-flex w-full items-center justify-center rounded-xl bg-[#2D2E30] px-5 py-3.5 text-sm font-bold text-white hover:bg-[#C97112] sm:w-auto">View latest payment</button> : null}<RejectedContent payment={payment} actionRequired={view.kind === "rejected"} onSubmit={onSubmit} /></section><ReceiptContext course={course} details={details} submittedAt={submittedAt} subdued /></>; }

function ProgressTracker({ left = false }) { const align = left ? "mx-0" : "mx-auto"; return <div className={`${align} mt-8 max-w-md`}><div className="flex items-start"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#4D7C57] text-white"><Check className="h-4 w-4" /></span><span className="mt-3 h-px flex-1 bg-[#7EAF85]" /><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#F8C56A] text-xs font-bold text-[#2D2E30] ring-4 ring-[#FFF4D8]">2</span><span className="mt-3 h-px flex-1 bg-[#D9CEBE]" /><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-[#D9CEBE] bg-[#FFFDF8] text-xs font-bold text-[#9A8775]">3</span></div><div className="mt-3 grid grid-cols-3 text-[11px] font-bold leading-4"><span className="text-left text-[#765F55]">Submitted</span><span className="text-center text-[#2D2E30]">Review</span><span className="text-right text-[#9A8775]">Access</span></div></div>; }

function RejectedContent({ payment, actionRequired, onSubmit }) { return <div className="mt-7 border-t border-[#D78A86]/30 pt-6"><div className="border-l-4 border-[#D78A86] pl-4"><p className="text-sm font-bold text-[#8E4039]">Reason from our team</p><p className="mt-2 text-sm leading-6 text-[#7D514C]">{payment.rejectReason || "Please submit a clear payment slip to continue."}</p></div>{shouldShowRejectedProof(payment) && <RejectedProofPreview paymentId={payment.id} />}{actionRequired ? <><p className="mt-6 text-sm leading-6 text-[#765F55]">Submit a new payment to continue your enrollment. This creates a new payment; the rejected payment remains in your order history.</p><button onClick={onSubmit} className="mt-5 inline-flex w-full items-center justify-center rounded-xl bg-[#2D2E30] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#C97112] sm:w-auto">Submit a new payment</button></> : <p className="mt-6 text-xs leading-5 text-[#765F55]">This rejected payment remains in your order history.</p>}</div>; }

function ReceiptContext({ course, details, submittedAt, subdued }) { return <section className={`border-y py-5 sm:py-6 ${subdued ? "border-[#2D2E30]/10" : "border-[#CDBEAA]"}`}><div className="flex items-center gap-3"><div className="h-14 w-[4.5rem] shrink-0 overflow-hidden rounded-xl bg-[#E7DCCE]">{course.image ? <img src={course.image} alt="" className="h-full w-full object-cover" /> : null}</div><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#C97112]">Your course</p><h2 className="mt-1 text-sm font-bold leading-5 text-[#2D2E30]">{course.title}</h2></div></div><div className="mt-5 border-t border-[#2D2E30]/10 pt-5 sm:flex sm:items-end sm:justify-between sm:gap-8"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#9A8775]">Amount paid</p><p className="mt-1 text-2xl font-bold tracking-tight text-[#B96128]">{details.amount}</p></div><dl className="mt-5 grid grid-cols-2 gap-x-6 gap-y-4 text-sm sm:mt-0 sm:min-w-[18rem]"><ReceiptDetail label="Payment method" value={details.method} /><ReceiptDetail label="Currency" value={details.currency} /><ReceiptDetail label="Submitted" value={submittedAt} /></dl></div></section>; }

function ReceiptDetail({ label, value }) { return <div><dt className="text-[10px] font-bold uppercase tracking-[.14em] text-[#9A8775]">{label}</dt><dd className="mt-1 text-sm font-semibold text-[#2D2E30]">{value}</dd></div>; }

function RejectedProofPreview({ paymentId }) {
  const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [proofBlob, setProofBlob] = useState(null); const [thumbnailUrl, setThumbnailUrl] = useState(""); const [modalUrl, setModalUrl] = useState(""); const [retryCount, setRetryCount] = useState(0);
  const cache = useRef(new Map()); const loadedRequestKey = useRef("");
  useEffect(() => {
    const requestKey = proofRequestKey(paymentId, retryCount);
    if (!shouldFetchProof({ paymentId, retryCount, loadedRequestKey: loadedRequestKey.current })) return undefined;
    let active = true; let nextUrl = "";
    const showProof = (blob) => { nextUrl = createProofObjectUrl(blob); if (!active) return revokeProofObjectUrl(nextUrl); setProofBlob(blob); setThumbnailUrl(nextUrl); setFailed(false); loadedRequestKey.current = requestKey; };
    (async () => { setLoading(true); setFailed(false); try { const blob = cache.current.get(paymentId) || await fetchRejectedPaymentProofBlob(paymentId); cache.current.set(paymentId, blob); showProof(blob); } catch { if (active) { setFailed(true); setThumbnailUrl(""); setProofBlob(null); } } finally { if (active) setLoading(false); } })();
    return () => { active = false; revokeProofObjectUrl(nextUrl); };
  }, [paymentId, retryCount]);
  useEffect(() => () => revokeProofObjectUrl(modalUrl), [modalUrl]);
  const state = rejectedProofDisplayState({ loading, failed, thumbnailUrl }); const open = () => proofBlob && setModalUrl(createProofObjectUrl(proofBlob)); const retry = () => setRetryCount((count) => count + 1);
  return <section className="mt-5"><p className="text-sm font-bold text-[#2D2E30]">Your submitted payment slip</p>{state === "loading" ? <div className="mt-3 flex w-full items-center gap-3 border-y border-[#2D2E30]/10 py-3"><div className="h-20 w-24 shrink-0 animate-pulse rounded-lg bg-[#F3E9D9]" /><p className="text-sm font-medium text-[#765F55]">Loading payment slip…</p></div> : state === "failed" ? <div className="mt-3 flex min-h-20 items-center justify-between gap-3 border-y border-[#2D2E30]/10 py-3"><p className="text-sm text-[#765F55]">Payment slip couldn&apos;t be loaded.</p><button type="button" onClick={retry} className="shrink-0 rounded-lg px-3 py-2 text-xs font-bold text-[#C97112] transition hover:bg-[#FFF4D8]">Try again</button></div> : <><button type="button" onClick={open} className="group mt-3 flex w-full items-center gap-3 border-y border-[#2D2E30]/10 py-3 text-left"><img src={thumbnailUrl} alt="Your submitted payment slip" className="h-20 w-24 rounded-lg object-cover transition-opacity duration-200" /><span><span className="block text-sm font-bold text-[#2D2E30]">Submitted payment slip</span><span className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-[#C97112]">View larger <Maximize2 size={13} /></span></span></button>{modalUrl && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#252527]/75 p-4 backdrop-blur-sm"><section className="relative w-full max-w-2xl rounded-2xl bg-[#FFFDF8] p-4 shadow-2xl"><button type="button" onClick={() => setModalUrl("")} className="absolute right-3 top-3 rounded-lg bg-white p-2 text-[#765F55] shadow-sm hover:bg-[#FFF4D8]" aria-label="Close payment slip"><X size={20} /></button><p className="mb-3 text-sm font-bold text-[#2D2E30]">Your submitted payment slip</p><img src={modalUrl} alt="Your submitted payment slip, enlarged" className="max-h-[75dvh] w-full rounded-xl object-contain" /></section></div>}</>}</section>;
}

export default OrderStatus;
