import { useEffect, useRef, useState } from "react";
import { Banknote, Check, ChevronDown, CreditCard, ImagePlus, Landmark, MoreHorizontal, Pencil, Plus, QrCode, ShieldCheck, Trash2, Wallet, X } from "lucide-react";
import ConfirmationModal from "../../components/ConfirmationModal";
import { createPaymentMethod, deletePaymentMethod, fetchPaymentMethods, setPaymentMethodActive, updatePaymentMethod } from "../../services/paymentMethodService";
import { methodDetails, typeLabel } from "./paymentMethodView";

const blank = () => ({ name: "", currency: "THB", type: "qr", provider: "manual", instructions: "", recipient: {}, isActive: true, adminPassword: "", qrImageFile: null });
const input = "mt-2 w-full rounded-xl border border-[#2D2E30]/15 bg-white px-3.5 py-3 text-sm text-[#2D2E30] outline-none transition placeholder:text-[#9B867C] focus:border-[#E58C1A] focus:ring-4 focus:ring-[#E58C1A]/10";
const label = "block text-sm font-bold text-[#2D2E30]";

function TypeIcon({ type, size = 18 }) { const Icon = type === "bank_transfer" ? Landmark : type === "wallet" ? Wallet : QrCode; return <Icon size={size} />; }
function FormSection({ title, description, children }) { return <section className="border-b border-[#2D2E30]/10 py-6 first:pt-0 last:border-0 last:pb-2"><div className="mb-4"><h3 className="font-bold text-[#2D2E30]">{title}</h3><p className="mt-1 text-sm leading-5 text-[#765F55]">{description}</p></div><div className="grid gap-4">{children}</div></section>; }
function StyledSelect({ label: selectLabel, value, onChange, options }) {
  const [open, setOpen] = useState(false); const root = useRef(null); const selected = options.find((option) => option.value === value) || options[0];
  useEffect(() => { const close = (event) => { if (!root.current?.contains(event.target)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const choose = (next) => { onChange(next); setOpen(false); };
  const onKeyDown = (event) => { if (event.key === "Escape") setOpen(false); if (event.key === "ArrowDown" || event.key === "Enter" || event.key === " ") { event.preventDefault(); setOpen((current) => !current); } };
  return <div ref={root} className="relative mt-2"><button type="button" aria-haspopup="listbox" aria-expanded={open} aria-label={selectLabel} onClick={() => setOpen((current) => !current)} onKeyDown={onKeyDown} className={`flex w-full items-center justify-between rounded-xl border bg-white px-3.5 py-3 text-left text-sm font-semibold text-[#2D2E30] outline-none transition focus:border-[#E58C1A] focus:ring-4 focus:ring-[#E58C1A]/10 ${open ? "border-[#E58C1A] ring-4 ring-[#E58C1A]/10" : "border-[#2D2E30]/15 hover:border-[#C97112]/50"}`}><span>{selected.label}</span><ChevronDown size={18} className={`text-[#765F55] transition ${open ? "rotate-180" : ""}`} /></button>{open ? <div role="listbox" aria-label={selectLabel} className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl border border-[#2D2E30]/10 bg-white p-1.5 shadow-xl shadow-[#2D2E30]/15">{options.map((option) => <button key={option.value} role="option" aria-selected={option.value === value} type="button" onClick={() => choose(option.value)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition ${option.value === value ? "bg-[#FFF1CE] text-[#9A5816]" : "text-[#2D2E30] hover:bg-[#FFF9EA]"}`}><span>{option.label}</span>{option.value === value ? <Check size={16} /> : null}</button>)}</div> : null}</div>;
}
function QrUpload({ preview, existingQr, file, onSelect }) {
  const image = preview || existingQr; const inputId = "payment-method-qr-upload";
  return <div className="flex items-center gap-3 rounded-xl border border-[#2D2E30]/10 bg-white p-3"><div className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-lg border ${image ? "border-[#2D2E30]/10 bg-[#FFFDF8]" : "border-dashed border-[#C97112]/35 bg-[#FFF9EA] text-[#C97112]"}`}>{image ? <img src={image} alt="Payment QR preview" className="h-full w-full rounded-lg object-contain p-1.5" /> : <QrCode size={24} strokeWidth={1.7} />}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-[#2D2E30]">{image ? "QR image ready" : "Add a QR image"}</p><p className="mt-0.5 truncate text-xs text-[#765F55]">{file ? file.name : image ? "Current QR image configured" : "PNG, JPG, WEBP or GIF · up to 5 MB"}</p></div><label htmlFor={inputId} className="inline-flex shrink-0 cursor-pointer items-center gap-1.5 rounded-lg border border-[#2D2E30]/15 bg-white px-3 py-2 text-sm font-bold text-[#2D2E30] transition hover:border-[#C97112] hover:bg-[#FFF4D8]"><ImagePlus size={15} />{image ? "Replace" : "Choose"}</label><input id={inputId} type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden tabIndex={-1} aria-hidden="true" onChange={(event) => onSelect(event.target.files?.[0] || null)} /></div>;
}

function MethodForm({ form, setForm, saving, onSubmit, onClose, error }) {
  const [preview, setPreview] = useState(""); const recipient = form.recipient || {};
  useEffect(() => { if (!form.qrImageFile) { setPreview(""); return undefined; } const url = URL.createObjectURL(form.qrImageFile); setPreview(url); return () => URL.revokeObjectURL(url); }, [form.qrImageFile]);
  const changeRecipient = (key, value) => setForm((current) => ({ ...current, recipient: { ...(current.recipient || {}), [key]: value } }));
  const isBank = form.type === "bank_transfer"; const isWallet = form.type === "wallet";
  return <div className="fixed inset-0 z-50 flex items-stretch justify-end bg-[#2D2E30]/45 backdrop-blur-[2px] sm:items-center sm:p-5"><section role="dialog" aria-modal="true" aria-labelledby="payment-method-form-title" className="flex h-full w-full max-w-2xl flex-col bg-[#FFFDF8] shadow-2xl sm:h-[min(92vh,900px)] sm:rounded-2xl">
    <header className="flex items-start justify-between border-b border-[#2D2E30]/10 bg-white px-5 py-5 sm:px-7"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#C97112]">Payment methods</p><h2 id="payment-method-form-title" className="mt-1 text-xl font-bold text-[#2D2E30] sm:text-2xl">{form._id ? "Edit payment method" : "Add payment method"}</h2><p className="mt-1 text-sm text-[#765F55]">Payments using this method are verified manually.</p></div><button type="button" onClick={onClose} disabled={saving} className="rounded-lg p-2 text-[#765F55] transition hover:bg-[#FFF4D8] hover:text-[#2D2E30]" aria-label="Close payment method form"><X size={21} /></button></header>
    <form id="payment-method-form" onSubmit={onSubmit} className="min-h-0 flex-1 overflow-y-auto px-5 py-6 sm:px-7">
      {error ? <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}
      <FormSection title="Basic information" description="Choose how students will see and use this payment option."><label className={label}>Method name<input required value={form.name} onChange={(e) => setForm((item) => ({ ...item, name: e.target.value }))} placeholder="e.g. PromptPay" className={input} /></label><div className="grid gap-4 sm:grid-cols-2"><div className={label}><span>Payment type</span><StyledSelect label="Payment type" value={form.type} onChange={(type) => setForm((item) => ({ ...item, type }))} options={[{ value: "qr", label: "QR payment" }, { value: "bank_transfer", label: "Bank transfer" }, { value: "wallet", label: "Wallet" }]} /></div><div className={label}><span>Currency</span><StyledSelect label="Currency" value={form.currency} onChange={(currency) => setForm((item) => ({ ...item, currency }))} options={[{ value: "THB", label: "THB (฿)" }, { value: "MMK", label: "MMK (Ks)" }]} /></div></div><label className="flex items-center gap-3 rounded-xl bg-[#FFF9EA] px-4 py-3 text-sm text-[#765F55]"><input type="checkbox" checked={form.isActive !== false} onChange={(e) => setForm((item) => ({ ...item, isActive: e.target.checked }))} className="h-4 w-4 accent-[#C97112]" /><span><strong className="text-[#2D2E30]">Available to students</strong><br />Students can select this method at checkout.</span></label></FormSection>
      <FormSection title="Recipient details" description={isBank ? "Add the bank details students need to make a transfer." : isWallet ? "Add the wallet details students need to send payment." : "Add the details students should verify before paying."}><label className={label}>{isBank ? "Account holder" : "Recipient name"}<input value={recipient.accountName || ""} onChange={(e) => changeRecipient("accountName", e.target.value)} placeholder={isBank ? "Account holder name" : "Recipient or business name"} className={input} /></label>{isBank ? <><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Bank name<input value={recipient.bankName || ""} onChange={(e) => changeRecipient("bankName", e.target.value)} placeholder="Bank name" className={input} /></label><label className={label}>Account number<input value={recipient.accountNumber || ""} onChange={(e) => changeRecipient("accountNumber", e.target.value)} placeholder="Account number" className={input} /></label></div><label className={label}>Reference hint <span className="font-normal text-[#9B867C]">(optional)</span><input value={recipient.referenceHint || ""} onChange={(e) => changeRecipient("referenceHint", e.target.value)} placeholder="What should students use as a transfer reference?" className={input} /></label></> : <div className="grid gap-4 sm:grid-cols-2"><label className={label}>{isWallet ? "Wallet or account ID" : "Account or reference number"}<input value={recipient.accountNumber || ""} onChange={(e) => changeRecipient("accountNumber", e.target.value)} placeholder={isWallet ? "Wallet ID" : "Account or reference number"} className={input} /></label><label className={label}>{isWallet ? "Wallet phone number" : "Contact phone number"} <span className="font-normal text-[#9B867C]">(optional)</span><input value={recipient.phoneNumber || ""} onChange={(e) => changeRecipient("phoneNumber", e.target.value)} placeholder="Phone number" className={input} /></label></div>}</FormSection>
      <FormSection title="Payment QR" description={form.type === "qr" ? "Add the QR image students will scan to pay." : "A QR image can be added if this payment option supports scanning."}><QrUpload preview={preview} existingQr={form.qrImage?.url || ""} file={form.qrImageFile} onSelect={(qrImageFile) => setForm((item) => ({ ...item, qrImageFile }))} /></FormSection>
      <FormSection title="Student instructions" description="Explain any steps students should follow after making their payment."><label className="sr-only" htmlFor="payment-instructions">Instructions</label><textarea id="payment-instructions" value={form.instructions} onChange={(e) => setForm((item) => ({ ...item, instructions: e.target.value }))} placeholder="For example: Transfer the exact amount, then upload your payment slip." className={`${input} min-h-28 resize-y`} maxLength={4000} /></FormSection>
      <FormSection title="Security confirmation" description="Confirm your admin password to save this payment method."><label className={label}>Admin password<input required autoComplete="current-password" type="password" value={form.adminPassword} onChange={(e) => setForm((item) => ({ ...item, adminPassword: e.target.value }))} placeholder="Enter your admin password" className={input} /></label></FormSection>
    </form><footer className="flex flex-col-reverse gap-3 border-t border-[#2D2E30]/10 bg-white px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl px-5 py-3 text-sm font-bold text-[#765F55] transition hover:bg-[#FFF4D8]">Cancel</button><button type="submit" form="payment-method-form" disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2D2E30] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#E58C1A] disabled:opacity-60"><ShieldCheck size={17} />{saving ? "Saving…" : form._id ? "Save changes" : "Add payment method"}</button></footer>
  </section></div>;
}

function MethodRow({ method, onEdit, onAction }) { const [open, setOpen] = useState(false); const details = methodDetails(method); const active = method.isActive; return <article className="relative flex flex-col gap-4 border-b border-[#2D2E30]/10 px-4 py-5 last:border-0 sm:px-6 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex items-start gap-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${active ? "bg-[#FFF1CE] text-[#C97112]" : "bg-[#F1EEEA] text-[#8B7B70]"}`}><TypeIcon type={method.type} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-base font-bold text-[#2D2E30] sm:text-lg">{method.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${active ? "bg-[#E9F4EA] text-[#246B35]" : "bg-[#F1EEEA] text-[#765F55]"}`}>{active ? "Active" : "Inactive"}</span></div><p className="mt-1 text-sm text-[#765F55]">{typeLabel(method.type)} · {method.currency}</p><p className="mt-1 truncate text-xs text-[#9B867C]">{details.summary || "No recipient details added"}{details.qr ? " · QR configured" : ""}</p></div></div><div className="flex items-center justify-between gap-3 border-t border-[#2D2E30]/10 pt-3 sm:border-0 sm:pt-0 lg:justify-end"><span className="text-xs font-medium text-[#9B867C]">{details.qr ? "QR configured" : method.type === "qr" ? "No QR image" : "Manual verification"}</span><div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} className="rounded-lg p-2 text-[#765F55] transition hover:bg-[#FFF4D8] hover:text-[#2D2E30]" aria-label={`Actions for ${method.name}`} aria-expanded={open}><MoreHorizontal size={20} /></button>{open ? <div className="absolute right-0 z-10 mt-1 w-44 overflow-hidden rounded-xl border border-[#2D2E30]/10 bg-white py-1 shadow-xl"><button onClick={() => { setOpen(false); onEdit(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm font-semibold text-[#2D2E30] hover:bg-[#FFF9EA]"><Pencil size={15} />Edit</button><button onClick={() => { setOpen(false); onAction("toggle", method); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm font-semibold text-[#2D2E30] hover:bg-[#FFF9EA]"><CreditCard size={15} />{active ? "Deactivate" : "Activate"}</button><button onClick={() => { setOpen(false); onAction("delete", method); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm font-semibold text-[#A34D45] hover:bg-[#FFF0EE]"><Trash2 size={15} />Remove</button></div> : null}</div></div></article>; }
function EmptyState({ onAdd }) { return <section className="py-16 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFF1CE] text-[#C97112]"><Banknote size={25} /></span><h2 className="mt-5 text-xl font-bold text-[#2D2E30]">No payment methods yet</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#765F55]">Add a payment method so students can choose how to pay.</p><button onClick={onAdd} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#2D2E30] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#E58C1A]"><Plus size={17} />Add payment method</button></section>; }

export default function PaymentMethods() {
  const [methods, setMethods] = useState([]); const [form, setForm] = useState(null); const [error, setError] = useState(""); const [formError, setFormError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [action, setAction] = useState(null); const [actionPassword, setActionPassword] = useState(""); const [actionError, setActionError] = useState("");
  const load = async () => { try { setLoading(true); setMethods(await fetchPaymentMethods()); } catch (e) { setError(e.message); } finally { setLoading(false); } }; useEffect(() => { load(); }, []);
  const closeForm = () => { if (!saving) { setForm(null); setFormError(""); } }; const save = async (event) => { event.preventDefault(); if (!form || saving) return; try { setSaving(true); setFormError(""); if (form._id) await updatePaymentMethod(form._id, form); else await createPaymentMethod(form); await load(); setForm(null); } catch (e) { setFormError(e.status === 403 ? "Incorrect admin password. Please try again." : e.message); } finally { setSaving(false); } };
  const openEdit = (method) => { setForm({ ...blank(), ...method, recipient: { ...(method.recipient || {}) }, adminPassword: "", qrImageFile: null }); setFormError(""); }; const openAction = (kind, method) => { setAction({ kind, method }); setActionPassword(""); setActionError(""); };
  const confirmAction = async () => { if (!actionPassword.trim()) return setActionError("Enter your admin password to continue."); try { setSaving(true); setActionError(""); const { kind, method } = action; if (kind === "toggle") await setPaymentMethodActive(method._id, !method.isActive, actionPassword); else { const result = await deletePaymentMethod(method._id, actionPassword); if (result.deactivated) setError(`${method.name} has payment history, so it was deactivated and kept for existing records.`); } setAction(null); await load(); } catch (e) { setActionError(e.status === 403 ? "Incorrect admin password. Please try again." : e.message); } finally { setSaving(false); } };
  const actionIsDelete = action?.kind === "delete";
  return <main className="min-h-full bg-[#FFFDF8] p-4 sm:p-6 md:p-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold text-[#2D2E30] sm:text-4xl">Payment methods</h1><p className="mt-2 text-sm text-[#765F55] sm:text-base">Manage the ways students can pay for courses.</p></div><button onClick={() => { setForm(blank()); setFormError(""); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2D2E30] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#E58C1A]"><Plus size={18} />Add payment method</button></header>{error ? <div role="alert" className="mb-5 flex items-start justify-between gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}<button onClick={() => setError("")} aria-label="Dismiss message"><X size={17} /></button></div> : null}{loading ? <div className="py-16 text-center text-sm text-[#765F55]">Loading payment methods…</div> : methods.length ? <section className="border-y border-[#2D2E30]/10 bg-white/45">{methods.map((method) => <MethodRow key={method._id} method={method} onEdit={() => openEdit(method)} onAction={openAction} />)}</section> : <EmptyState onAdd={() => setForm(blank())} />}{form ? <MethodForm form={form} setForm={setForm} saving={saving} onSubmit={save} onClose={closeForm} error={formError} /> : null}{action ? <ConfirmationModal isOpen title={actionIsDelete ? "Remove payment method" : `${action.method.isActive ? "Deactivate" : "Activate"} payment method`} message={actionIsDelete ? <><strong>{action.method.name}</strong> will be removed if it has no payment history. If students have used it before, it will be deactivated instead and those historical records will remain unchanged.</> : <>{action.method.isActive ? "Students will no longer be able to choose this method at checkout." : "Students will be able to choose this method at checkout."}</>} confirmText={actionIsDelete ? "Remove method" : action.method.isActive ? "Deactivate method" : "Activate method"} isDangerous={actionIsDelete || (action.kind === "toggle" && action.method.isActive)} password={actionPassword} onPasswordChange={setActionPassword} error={actionError} isSaving={saving} onConfirm={confirmAction} onCancel={() => !saving && setAction(null)} /> : null}</div></main>;
}
